[package]
name = "pasted"
version = "1.1.0"
edition = "2021"
authors = ["drakeerv <drakeerv@outlook.com>"]
description = "A pastebin frontend written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
byte-unit = "5.1.4"
chrono = { version = "0.4.38", default-features = false }
once_cell = "1.19.0"
scraper = "0.19.0"
serde = { version = "1.0.199", features = ["derive"] }
tera = "1.19.1"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros", "signal"] }
ureq = { version = "2.9.7", features = ["cookies"] }
ureq_multipart = "1.1.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
strip = true
