[package]
name = "pasted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
base64 = "0.22.1"
lazy_static = "1.4.0"
reqwest = { version = "0.12.4", features = ["multipart", "cookies"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
tera = "1.19.1"
tl = "0.7.8"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros", "signal"] }
