# Example docker compose for pasted

services:
  pasted:
    image: ghcr.io/dragynfruit/pasted:latest
    container_name: "pasted"
    ports:
      - "3000:3000"
    volumes:
      - "/data/pasted/cache:/usr/local/bin/pasted/cache"
